name: Deploy Static Website

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: pulumi login

      - name: Set AWS OIDC Role ARN from GitHub Secrets
        run: echo "ROLE_ARN=${{ secrets.AWS_ROLE_ARN }}" >> $GITHUB_ENV

      - name: Debug Role ARN
        run: echo "Using AWS Role ARN: $ROLE_ARN"

      - name: Configure AWS OIDC Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          role-session-name: GitHubActionsSession
          aws-region: us-east-1

      - name: Install Pulumi Dependencies
        run: |
          pip install pulumi pulumi-aws

      - name: Deploy with Pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: |
          pulumi stack select dev
          pulumi up --yes
